In [40]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)
print(a.size)
print(a)

1
(3,)
3
[1 2 3]


In [13]:
b=np.ones((2,3))
print(b.size)
print(b.shape)
print(b.ndim)
print(b)

6
(2, 3)
2
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# 最小维度 
a = np.array([1, 2, 3, 4, 5], ndmin =  2)
print (a)

[[1 2 3 4 5]]


In [32]:
a = np.array([1,  2,  3.21], dtype=np.complex64)  
print (a)

[1.  +0.j 2.  +0.j 3.21+0.j]


In [42]:
dt = np.dtype([('age', np.int8), ('height', np.float32)])
a = np.array([[(10,1),(20,2),(30,3)], [(10,1),(20,2),(30,3)]], dtype = dt) 
print(a['age'])
print(a['height'])
print(a.ndim)
print(a.dtype)
print(a.itemsize)

[[10 20 30]
 [10 20 30]]
[[1. 2. 3.]
 [1. 2. 3.]]
2
[('age', 'i1'), ('height', '<f4')]
5


In [50]:
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)
print(b)

1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [52]:
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

