In [8]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)
print(a.size)
print(a)

1
(3,)
3
[1 2 3]


In [13]:
b = np.ones((2, 3))
print(b.size)
print(b.shape)
print(b.ndim)
print(b)

6
(2, 3)
2
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# 最小维度 
a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [32]:
a = np.array([1, 2, 3.21], dtype=np.complex64)
print(a)

[1.  +0.j 2.  +0.j 3.21+0.j]


In [42]:
dt = np.dtype([('age', np.int8), ('height', np.float32)])
a = np.array([[(10, 1), (20, 2), (30, 3)], [(10, 1), (20, 2), (30, 3)]], dtype=dt)
print(a['age'])
print(a['height'])
print(a.ndim)
print(a.dtype)
print(a.itemsize)

[[10 20 30]
 [10 20 30]]
[[1. 2. 3.]
 [1. 2. 3.]]
2
[('age', 'i1'), ('height', '<f4')]
5


In [50]:
a = np.arange(24)
print(a.ndim)  # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2, 4, 3)  # b 现在拥有三个维度
print(b.ndim)
print(b)

1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [52]:
x = np.array([1, 2, 3, 4, 5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [4]:
four = np.array([[1, 2, 3], [4, 5, 6]])
# 修改的是原有的
four.shape = (3, 2)
print(four)
# 返回一个新的数组
four = four.reshape(3, 2)
print(four)
# 将多维变成一维数组
five = four.reshape((6,), order='F')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')
print(five)
print(six)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 3 5 2 4 6]


In [11]:
x = [(1, 2, 3), (4, 5, 6)]
a = np.asarray(x)
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
s = b'hello world'
print(type(s))
ret = np.frombuffer(s, dtype='S1')
print(ret)

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [29]:
l = range(10)
it = iter(l)
ret = np.fromiter(it, dtype=np.int64)
print(ret)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
a = np.arange(10)
b = slice(0, 10, 2)
print(a[b])

[0 2 4 6 8]


In [33]:
b = a[2:7:2]
print(b)

[2 4 6]


In [43]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

# 获取第一个二维数组
# print(arr[0, :, :])
# [[1 2]
#  [3 4]]

# 获取所有数组的第一个元素
print(arr[:, :, 0:1])
# [[1 3]
#  [5 7]]

# 获取特定范围的子数组
#print(arr[:, 0:1, :])
# [[[1 2]]
#  [[5 6]]]

[[[1]
  [3]]

 [[5]
  [7]]]


# NumPy 数组切片的基本语法是 array[start:stop:step]，对于多维数组则是用逗号分隔不同维度的切片：
三维数组是一种具有三个独立维度的数据结构，可以看作是二维数组的扩展。它通过三个索引（通常表示为 [i][j][k]）唯一确定元素的位置，其中：

    第一维（i）：通常表示层或深度，例如三维空间中的不同平面；
    第二维（j）：表示行；
    第三维（k）：表示列

其结构类似一个立方体，或者由多个二维数组堆叠而成。例如，在编程中，int array[3][4][2] 表示一个包含3层、每层4行2列的三维数组
。

In [48]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

[1 4 5]


In [52]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('我们的数组是：')
print(x)
print('\n')
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
z = x[[0, 0, 3, 3], [0, 2, 0, 2]]
print('这个数组的四个角元素是：')
print(y)
print(z)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]
[ 0  2  9 11]


# 广播就是将不同位的的矩阵进行相加，但是要求有一个对应的维度是相同的
广播的核心思想是自动扩展较小的数组，使其形状与较大的数组兼容，从而进行逐元素操作。

In [60]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(bb)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [67]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [69]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print('原始数组是：')
print(a)
print('\n')
print('原始数组的转置是：')
b = a.T
print(b)
print('\n')
print('以 C 风格顺序排序：')
c = b.copy(order='C')
print(c)
for x in np.nditer(c):
    print(x, end=", ")
print('\n')
print('以 F 风格顺序排序：')
c = b.copy(order='F')
print(c)
for x in np.nditer(c):
    print(x, end=", ")

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以 C 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以 F 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [79]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print('原始数组是：')
print(a)
print('\n')
print('修改后的数组是：')
for x in np.nditer(a.T, flags=['external_loop'], order='C'):
    print(x, end=", ")

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 

In [81]:
a = np.arange(9).reshape(3, 3)
print('原始数组：')
for row in a:
    print(row)

#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print('迭代后的数组：')
for element in a.flat:
    print(element)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8


In [88]:
a = np.arange(9).reshape(3, 3)
# K 内存中出现的顺序 A 原顺序 C 按照行展开 F 按照列展开 
b = a.flatten(order='c')
print(b)

[0 1 2 3 4 5 6 7 8]


In [94]:
t = np.arange(0, 10).reshape(2, 5)
print(t)
t[0, 4:] = 0
print(t)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 0]
 [5 6 7 8 9]]


In [98]:
t = np.arange(5, 20).reshape(3, 5)
print(t)
t[t < 10] = 0
print(t)


[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  0  0  0  0]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [100]:
score = np.array([[80, 88], [82, 81], [75, 81]])
# 三木运算符 np.where(条件, True, False)条件为真则输出True条件为假则为False
result = np.where(score > 80, True, False)
print(result)

[[False  True]
 [ True  True]
 [False  True]]


In [103]:
score = np.array([[80, 88], [82, 81], [75, 81]])
# 限制最大值和最小值
a = score.clip(80, 85)
print(a)

[[80 85]
 [82 81]
 [80 81]]


In [109]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [119]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# 沿轴0插入行（在索引1处插入新行）
new_row = np.array([[7, 8]])
result = np.insert(arr, 1, new_row, axis=0)
print(result)

# 沿轴1插入列（在索引1处插入新列）
new_col = np.array([[9], [10], [11], [12]])
result = np.insert(arr, 1, new_col, axis=1)
print(result)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]
[[ 1  9 10 11 12  2]
 [ 3  9 10 11 12  4]
 [ 5  9 10 11 12  6]]


In [123]:
a = np.arange(12).reshape(3, 4)
print(a)
print(np.delete(a, 1))
print(np.delete(a, 2, axis=0))
print(np.delete(a, 2, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  3  4  5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


# numpy.unique() 函数用于查找数组中的唯一元素（去重），并可以返回排序后的结果以及相关的索引信息
return_index是否返回唯一元素的原始索引（首次出现位置）

return_inverse是否返回重建原始数组的索引

return_counts是否返回每个唯一元素出现的次数

In [129]:
a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
print('第一个数组：')
print(a)
# print ('\n')
# print ('第一个数组的去重值：')
# u = np.unique(a)
# print (u)
# print ('\n')
# print ('去重数组的索引数组：')
# u,indices = np.unique(a, return_index = True)
# print(u)
# print (indices)
# print ('\n')
# print ('我们可以看到每个和原数组下标对应的数值：')
# print (a)
print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print(indices)
print('\n')
print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [131]:
# 5. 数据的比较
a = np.arange(12).reshape(3, 4)
result = np.maximum(a, 3)
# 第一个参数中的每一个数与第二个参数比较返回大的
print(result)

[[ 3  3  3  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [135]:
score = np.array([[80, 88], [82, 81], [75, 81]])
print(np.mean(score, axis=0))

[79.         83.33333333]


In [137]:
arr = np.arange(8).reshape(2, 2, 2)
print(arr)
print(np.cumsum(arr, axis=0))
# 输出:
# [[[0 1]
#   [2 3]]
#
#  [[0+4 1+5] → [4 6]
#   [2+6 3+7]] → [8 10]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  6]
  [ 8 10]]]


In [140]:
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)
#这样我们就可以知道最小的 81 是第二排的，是从前往后遍历的
print(result, res)

[[80 88]
 [82 81]
 [75 81]]
[2 1] [75 81]


In [142]:
# 标准差
result = np.std(score, axis=0)
print(result)
# 10. 极 值
result = np.ptp(score, axis=None)  #就是最大值和最小值的差
print(result)

[2.94392029 3.29983165]
13


In [148]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# 要求 a,b 两个数组的维度相同
# print ('沿轴 0 连接两个数组：')
# print (np.concatenate((a,b),axis= 0))
# print ('\n')
# print ('沿轴 1 连接两个数组：')
# print (np.concatenate((a,b),axis = 1))
# 2. 根据轴进行堆叠
print('沿轴 0 连接两个数组：')
print(np.stack((a, b), axis=0))
print('\n')
print('沿轴 1 连接两个数组：')
print(np.stack((a, b), axis=1))
print('\n')
print('沿轴 2 连接两个数组：')
print(np.stack((a, b), axis=2))

沿轴 0 连接两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 连接两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


沿轴 2 连接两个数组：
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# axis越来越深0，1，2

In [146]:
red = np.random.rand(256, 256)
green = np.random.rand(256, 256)
blue = np.random.rand(256, 256)
rgb = np.stack((red, green, blue), axis=2)
print(rgb.shape)

(3, 256, 256)


In [149]:
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [150]:
# 4. 矩阵水平拼接
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [151]:
arr = np.arange(9).reshape(3, 3)
print('将数组分为三个大小相等的子数组：')
b = np.split(arr, 3)
print(b)

将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [160]:
arr = np.array([
    [1, 2, 3, 4],  # 第0行
    [5, 6, 7, 8],  # 第1行
    [9, 10, 11, 12]  # 第2行
])
b, c = np.split(arr, [0], axis=0)
print(b)
print(c)
# print(d)


[]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [165]:
# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10 * np.random.random((2, 6)))
print('原 array：')
print(harr)
print('拆分后：')
print(np.hsplit(harr, [2, 3]))

原 array：
[[5. 8. 9. 6. 0. 3.]
 [9. 3. 7. 0. 2. 9.]]
拆分后：
[array([[5., 8.],
       [9., 3.]]), array([[9.],
       [7.]]), array([[6., 0., 3.],
       [0., 2., 9.]])]


In [166]:
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [171]:
t = np.arange(24, dtype=float).reshape(4, 6)
# 将三行四列的数改成 nan
t[3, 4] = np.nan
print(t)
print(np.count_nonzero(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
23


In [172]:
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [173]:
t = np.arange(24).reshape(4, 6).astype('float')  #
# 将数组中的一部分替换 nan
t[1, 3:] = np.nan
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [180]:
# a = np.arange(12).reshape(3, 4)
# print('原数组：')
# print(a)
# print('\n')
# print('对换数组：')
# print(np.transpose(a))
# # 与 transpose 一致
# a = np.arange(12).reshape(3, 4)
# print('原数组：')
# print(a)
# print('\n')
# print('转置数组：')
# print(a.T)
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re = t1.swapaxes(0, 1)
print(' 原 数 组 ：')
print(t1)
print('\n')
print('调用 swapaxes 函数后的数组：')
print(re)
t = np.rollaxis(t, 3, 0)
print(t.shape)

 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


AxisError: axis 3 is out of bounds for array of dimension 2

In [182]:
# 创建一个三维数组
a = np.ones((3, 4, 5))

# 将轴2滚动到位置0
b = np.rollaxis(a, 2)
print(b.shape)  # 输出: (5, 3, 4)

# 将轴0滚动到位置2
c = np.rollaxis(a, 0, 2)
print(c.shape)  # 输出: (4, 3, 5)

(5, 3, 4)
(4, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
